title: Aventus Improvement Proposals
description: >- # this means to ignore newlines until "baseurl:"
    Aventus is a scalable, sustainable and interoperable parachain that makes building on Polkadot, Ethereum and beyond accessible for companies in any ecosystem.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aips.aventus.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aventusnetwork
github_username: Aventus-Network-Services
github:
    aip_repo: https://github.com/Aventus-Network-Services/AIPs
source: .

header_pages:
    - all.html
    - core.html
    - layer_1.html
    - interface.html
    - ecosystem.html
    - informational.html

# Build settings
highlighter: rouge
markdown: kramdown
theme: jekyll-theme-leap-day
kramdown:
    parse_block_html: false
    auto_ids: true
    # This is to ensure more deterministic behaviour
    auto_id_stripping: true
    syntax_highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-seo-tag

defaults:
    - scope:
          path: "AIP"
      values:
          layout: "default"

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - .github
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
    - README.md

include:
    - LICENSE

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
